import React from 'react'
import type { Metadata } from "next";

import { Footer } from '@/app/_components/footer';
import { Header } from '@/app/_components/header';

import { Toaster } from '@/components/ui/sonner';

import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
    return (
        <html lang="en">
            <body>
                <main className='flex min-h-screen flex-col'>
                    <Header />
                    {children}
                    <Footer />
                </main>
                <Toaster />
            </body>
        </html>
    )
}

export default RootLayout