import React from 'react'
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const Layout = ({
    cards,
    table,
}: {
    cards: React.ReactNode
    table: React.ReactNode
}) => {
    return (
        <section className='flex flex-col gap-4 bg-primary-foreground p-4'>
            {cards}
            {table}
        </section>
    )
}

export default Layout
